### ISSUE TITLE
IsChatOpen and IsDialogOpen missing

### ISSUE THREAD

**Issue by BigBrainAFK** [SAMPProjects/Open-SAMP-API#10]
As the title sais these two functions are missing and they are the functions I use the most and most other APIs or SAMPD UDF just have IsChatOpen which combines them... I need them seperated so that I can make checks if the dialog has opened or not and more stuff like that.

**Comment by agrippa1994** [comment]
It's the same case like on #11. It should also be possible, but there's no time at the moment :(

**Comment by BigBrainAFK** [comment]
Well it is possible as your old API with minikahn had these two functions and they still work
