### ISSUE TITLE
GetPlayerSkinID

### ISSUE THREAD

**Issue by BigBrainAFK** [SAMPProjects/Open-SAMP-API#11]
Is it possible to make something like that? I saw it in SAMP-UDF I think and it would be awesome if we could use it with this api too.

**Comment by agrippa1994** [comment]
Yes, it would be definitely possible, but I haven't got enough time at the moment due to my occupation

**Comment by marcelgerber** [comment]
@BigBrainAFK I've looked for the right memory offset, but haven't found one, neither on http://www.gtamodding.com/wiki/Memory_Addresses_%28SA%29 nor in one of the two SAMP-UDF libraries. You though said it was available in some SAMP-UDF version. Can you maybe point out where exactly you found this?

**Comment by BigBrainAFK** [comment]
Well I must have misread something because i can't find it either.

Sorry for causing that much trouble.

**Comment by mschnitzer** [comment]
@MarcelGerber 0xB6F5F0 CPED Pointer + 0x22 (2 Byte)
![skin](https://cloud.githubusercontent.com/assets/8287131/8884073/0be1e8d0-3254-11e5-9d4b-d0b0fa42b43a.png)

That is tested.

**Comment by marcelgerber** [comment]
Thanks. Implemented in 43724e3705ebf35db61b19e54f3db879095856b8.

Binaries coming soon.
