### ISSUE TITLE
UpdatePlayerData doesn't work

### ISSUE THREAD

**Issue by marcelgerber** [SAMPProjects/Open-SAMP-API#16]
Over here, [`UpdatePlayerData`](https://github.com/SAMPProjects/Open-SAMP-API/blob/90156ad0dce08441b5fff564217d7be73dd31941/src/Open-SAMP-API/Game/SAMP/RemotePlayer.cpp#L65-L78) doesn't seem to work. Calling `GetPlayerNameByID` and related functions will result in an empty result, until I open up the player dialog (by pressing Tab in SAMP) for the first time. Afterwards, it works as expected.

Using SAMP 0.3.7 on Windows 8.1

Affected functions: `GetPlayerIDByName`, `GetPlayerNameByID`, `GetPlayerId`

**Comment by marcelgerber** [comment]
Maybe the [pattern](https://github.com/SAMPProjects/Open-SAMP-API/blob/90156ad0dce08441b5fff564217d7be73dd31941/src/Open-SAMP-API/Game/SAMP/PatternTable.hpp#L69-L70) did change in 0.3.7?

**Comment by ghost** [comment]
Yes, the pattern has changed.
But also some RemotePlayer functions don't work as excpected

**Comment by ghost** [comment]
Also `GetPlayerNameByID` need to fetch the base pointer (It's the player pool) so anyone need to call `GetPlayerNameByID` first (e.g. the scoreboard or player tags).
So to fix the problem, first we need to sampStructure pointer, then the pools pointer and then the pointer of the player pool.

**Comment by agrippa1994** [comment]
In the current implementation these functions are fetched from the "draw name tag" function. (Just look for %s (%d) in IDA, whose pattern stands for the name tag string).
To make this feature version unindependent we have to rely on the current implementation because pointer offsets could change in the future. I think, that adjusting the pattern would fix this bug :)

**Comment by ghost** [comment]
I've checked both pattern (`GetPlayerNameByID` and `UpdatePlayerData`), `UpdatePlayerData` was faulty and was fixed with da1c40d203b05ab234f898c5b9b645aec96e69c5

**Comment by agrippa1994** [comment]
Released in [2.0.7](https://github.com/SAMPProjects/Open-SAMP-API/releases/tag/2.0.7)
