### ISSUE TITLE
Get weapon info from player

### ISSUE THREAD

**Issue by mschnitzer** [SAMPProjects/Open-SAMP-API#19]
Taken from here: http://forum.samp-api.net/index.php?page=Thread&postID=32#post32

We should add these functions to our API:
- GetPlayerWeaponID()
- GetPlayerWeaponType()

**Comment by ghost** [comment]
Added with 0a34ec61751c42b860db1dfd3973c7625ac446ab
Only need to be compiled

**Comment by marcelgerber** [comment]
I updated the compiled binaries in 33f20f666f95789db2b5fa963112bfaadcec7866.
