### ISSUE TITLE
GetVehicleHealth constantly returns '4'

### ISSUE THREAD

**Issue by mschnitzer** [SAMPProjects/Open-SAMP-API#20]
Taken from here: http://forum.samp-api.net/index.php?page=Thread&postID=33#post33

It seems that GetVehicleHealth reports constantly `4`.

**Comment by ghost** [comment]
Returns the right value in C++. Bug in AHK file?

**Comment by mschnitzer** [comment]
I have no idea. I just reported the bug for another user.

**Comment by marcelgerber** [comment]
Assuming they use the AHK include, I already fixed that bug in https://github.com/SAMPProjects/Open-SAMP-API/commit/5498877063c11af38c77cba8bec324a72a184e34. Maybe they're using an old version of the include.

**Comment by marcelgerber** [comment]
I just confirmed this doesn't happen with the latest version in combination with AHK.
Thus, closing.
