### ISSUE TITLE
Add ScreenToWorld vector

### ISSUE THREAD

**Issue by Crayder** [SAMPProjects/Open-SAMP-API#23]
Basically,
Input: Screen coordinates.
Output: X, Y, Z directional vector.

If the camera is facing exactly south the output for `320, 240` (center screen coordinates on a 640, 480 screen) would be `0, -1, 0`.

**Comment by marcelgerber** [comment]
Implemented in 2eab35167c5f48abf1a390a0000d902c8764c056, binary already included.
Closing.
