### ISSUE TITLE
Hooks.hpp: apply ohne args?

### ISSUE THREAD

**Issue by LuxXx** [SAMPProjects/Open-SAMP-API#34]
Hi!
Der Code ist echt sauber!
Am meisten gefällt mir wie die Detours (Hook.hpp) umgesetzt wurden. Vorallem in Kombination mit Lambda-Funktionen, macht eure Implementation das Leben um einiges schöner.
Ich hab noch nicht soviel mit variadischen templates gearbeitet, trotzdem hab ich mich gefragt, wie ich mit euren Code einen Hook für eine Funktion ohne Parameter applied.
Du hast folgendes stehen:
`template<CallConvention cc, typename retn, typename ...args>`
Was ist, wenn wir gar keine args haben? Kommt ja häufiger vor. ;)
Wär cool, wenn dieser Fall noch abgedeckt wird, auch wenn ihr es gar nicht nutzt.

Gruß
LuxXx

@agrippa1994

**Comment by agrippa1994** [comment]
Hi,
danke vielmals :)
Variadic Templates können auch 0 Elemente annehmen, von dem her ist dieser Case schon abgedeckt. 

Gruß

**Comment by LuxXx** [comment]
Okay, dann hab ich wohl irgendwas falsch gemacht.
EDIT: Habs grad nochmal getestet, geht doch ^^
