### ISSUE TITLE
Can I create dll (.asi) files using this API?

### ISSUE THREAD

**Issue by Hidend** [SAMPProjects/Open-SAMP-API#37]
Im having a lot of problems trying to create an asi file, and well, title is my question, it's possible to create an asi file using this API?

**Comment by ghost** [comment]
What do you mean specifically?
Do you ask if your ASI can call this API? 
Yes you can. Just normally initialize the API.

Do you ask if you can convert your DLL to an ASI with this API? 
No you cant, because an ASI is just an DLL. So you just need to change the extension from `dll` to `asi`

**Comment by agrippa1994** [comment]
Yes this should be possible by changing the file extension. Why do you want to use the API in that way?

**Comment by Hidend** [comment]
Somehow, it doesn't work for me as ASI. Well, it would be easier as people could use a ModLoader

**Comment by ghost** [comment]
Well, the ASI Loader is an Mod Loader. Can you send us an step-by-step instruction or a reproduceable example, that is published on GitHub?
Then I take a look at it.
