### ISSUE TITLE
IsPlayerInRange2D and IsPlayerInRange3D doesnt work

### ISSUE THREAD

**Issue by TheFilet** [SAMPProjects/Open-SAMP-API#4]
Hello
The functions IsPlayerInRange2D and IsPlayerInRange3D doesnt work. Even if I select a radius of 3000 it always returns 0

**Comment by agrippa1994** [comment]
Do functions like GetPlayerZ oder GetPlayerX work? Maybe there's a problem with reading data from the remote process

**Comment by TheFilet** [comment]
GetPlayerPos works fine.

**Comment by ghost** [comment]
I'm check it at the weekend.

**Comment by marcelgerber** [comment]
Should have been fixed with 41371afe212fd72cb73cc1531fad31814e024b34 - there was a bug in `GetPlayerPosition`. That bug shouldn't have affected `IsPlayerInRange2D`, though.

Could you please check back as soon as new binaries are available?

**Comment by TheFilet** [comment]
I'll check as soon as the new libs are out

**Comment by mschnitzer** [comment]
@TheFilet The new binaries are out: http://download.samp-api.net/3aa2bb0cef461a0ed6cef8cd/

If it still doesn't work, you can re open that issue.
