### ISSUE TITLE
.dll files always not found

### ISSUE THREAD

**Issue by RobbyAJM** [SAMPProjects/Open-SAMP-API#49]
I always failed to include the SAMP_API.ahk because it always say "The dll-file couldn't be found!"
What I've tried:

1. Check the hModule output and it show "0" (The documentation says zero means "Success" but I never success to run any SAMP Functions)
2. Removing the hModule if statements for bypassing the dll validation 
3. Recompile the .dll file through Visual Studio 2013
4. Checking the .dll path and it's 100% correct, not an invalid path
5. I've try change the dll file path to a random path to make sure what does it will return. But the hModule still return 0 (Which by documentation meaning succes but actually not success), 
6. I've check my compiled .dll files and seems all function are in ([screenshot ](https://ibb.co/FBHVFz9))

This is the whole Visual Studio 2013 logs
> 1>------ Build started: Project: Open-SAMP-API, Configuration: Release Win32 ------
> 1>  Client.cpp
> 1>  GTAFunctions.cpp
> 1>  MemoryFunctions.cpp
> 1>  PlayerFunctions.cpp
> 1>  RenderFunctions.cpp
> 1>  SAMPFunctions.cpp
> 1>  VehicleFunctions.cpp
> 1>  WeaponFunctions.cpp
> 1>  dllmain.cpp
> 1>  Game.cpp
> 1>  World.cpp
> 1>  Messagehandler.cpp
> 1>  Box.cpp
> 1>  D3DFont.cpp
> 1>  dx_utils.cpp
> 1>  Image.cpp
> 1>  Line.cpp
> 1>  RenderBase.cpp
> 1>  Renderer.cpp
> 1>  Text.cpp
> 1>  RemotePlayer.cpp
> 1>  SAMP.cpp
> 1>  Memory.cpp
> 1>  NakedHook.cpp
> 1>  Process.cpp
> 1>  Module.cpp
> 1>  Pattern.cpp
> 1>  PipeClient.cpp
> 1>  PipeServer.cpp
> 1>  Serializer.cpp
> 1>     Creating library C:\projects\Open-SAMP-API\src\..\bin\Open-SAMP-API.lib and object C:\projects\Open-SAMP-API\src\..\bin\Open-SAMP-API.exp
> 1>  Generating code
> 1>  All 3132 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
> 1>  Finished generating code
> 1>  Open-SAMP-API.vcxproj -> C:\projects\Open-SAMP-API\src\..\bin\Open-SAMP-API.dll
> 1>  Open-SAMP-API.vcxproj -> C:\projects\Open-SAMP-API\src\..\bin\Open-SAMP-API.pdb (Full PDB)
> ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
>

**Comment by agrippa1994** [comment]
Hi,

as far as I can remember, AHK distributes two versions. One version is for Unicode and the other one is ANSI. Please try the ANSI version.

**Comment by RobbyAJM** [comment]
That's cool. It's work now, Thank you so much!

**Comment by agrippa1994** [comment]
You are welcome :)
