### ISSUE TITLE
How to get the commands entered to the chat?

### ISSUE THREAD

**Issue by DestroyerDarkNess** [SAMPProjects/Open-SAMP-API#50]
Is there no function to register commands to the chat and get the commands entered to the chat?

**Comment by agrippa1994** [comment]
No, there is unfortunately no mechanism to register your own chat callbacks 🤷‍♂️

**Comment by DestroyerDarkNess** [comment]
I understand, is it possible to have a function to obtain the last command entered in the chat?

That would be enough, I would just loop that function. and ready.

**Comment by DestroyerDarkNess** [comment]
Already solved.

For those looking for a solution, Please Check my Plugin: [GameExitFix](https://github.com/DestroyerDarkNess/GameExitFix)
