### ISSUE TITLE
GetVehicleHealth doesn't work

### ISSUE THREAD

**Issue by marcelgerber** [SAMPProjects/Open-SAMP-API#6]
For me, `GetVehicleHealth()` always returns 4 while in a vehicle, no matter the car damage.
Furthermore, when not in a car, it returns 0 rather than the -1 it's supposed to return.

The address is correct, though, I've checked in Cheat Engine for myself. The data type, float, is correct as well.
Weird.

**Comment by ghost** [comment]
I'm check it at the weekend.

**Comment by marcelgerber** [comment]
Sorry, it was a flaw in my own code (and the AHK include).
Fixed in 5498877063c11af38c77cba8bec324a72a184e34
