### ISSUE TITLE
Create MakeFile 

### ISSUE THREAD

**Issue by JohnnyCrazy** [SAMPProjects/Open-SAMP-API#7]
Since we plan to move our binaries to GitHub-Releases, we also want to implement TravisCI's automatic builds.

The `.travis.yml` +  TravisCI Hooks are already setup locally, we just need a good/working MakeFile. Since I have no clue how to create them at all (C++ noob), maybe someone can help us out?

**Comment by mschnitzer** [comment]
I think I can help there. I will have a talk with @agrippa1994

**Comment by ghost** [comment]
I think its with AppVeyor done.

**Comment by agrippa1994** [comment]
Thanks for closing this issue. By the way, as far as I know, Travis doesn't support Windows builds unfortunately :(
