### ISSUE TITLE
Overlay: No support for special chars (like umlauts)

### ISSUE THREAD

**Issue by marcelgerber** [SAMPProjects/Open-SAMP-API#8]
See the left part of the screenshot below, where it says `Nova-Ort: SF Burger Shot Sd`. It's supposed to say `Nova-Ort: SF Burger Shot Süd` (notice the missing `ü`).

![sa-mp-001](https://cloud.githubusercontent.com/assets/2641501/7434555/f1140f92-f03b-11e4-8741-015d205069b9.png)

**Comment by ghost** [comment]
It's uncompatible because the DrawText-Method in CD3DFont can only handle TCHAR, aka. 8 bits.
@agrippa1994

**Comment by agrippa1994** [comment]
CD3DFont can only handle US-ASCII characters.
The font engine needs to be rewritten to ID3DXFont which can handle Unicode symbols as well. But I don't know when I've got enough time for that

**Comment by ghost** [comment]
So we need to change the implementation to `std::wstring`  (UTF-16)? 
There are some converting functions in WIN32, so it should work fine with `std::string`

**Comment by agrippa1994** [comment]
I don't know if this would fix the problem. Is SendChat or another command with characters like öäü possible? If so, we've to change the implementation of CD3DFont

**Comment by ghost** [comment]
@agrippa1994 Umlauts in the example of C++ are available in SendChat.
If we change the implementation, we would support full ANSI and `std::string` limits us (but should be okay).

**Comment by agrippa1994** [comment]
Especially for this issue, we need to implement the encoding in CD3DFont (afaik). Maybe there is a working implementation out there but consider implementing the color embedding system.

Before I implemented the color embedding system into CD3DFont, the API used ID3DXFont for drawing all fonts. ID3DXFont can handle umlauts as well but I didn't find a way to embed colors in the text. It should be possible to implement this behavior because ID3DXFont :)

**Comment by ghost** [comment]
Fixed with 6469f010739e5f8ece1f699da68a2224ea1bd46d

![](https://cloud.githubusercontent.com/assets/2185647/21955059/e50891e2-da62-11e6-88dc-1e62c20a11d3.png)
The code should also be checked for bugs (even I used this implementation in an full Unicode project for about an year)

**Comment by agrippa1994** [comment]
Wow! I really love it, great work 👍 Thanks for that :)
